### ISSUE TITLE
 screenType issue 

### ISSUE THREAD

**Issue by HamzaMahmood1999** [CoderUni/responsive_sizer#10]
The method to set screenType between mobile or tablet gives the wrong input on certain tablets whose height in landscape mode is shorter than 600. I suggest lowering the "magic number" to check height in landscape mode to 550 from 600 to support tablets with smaller screens

**Comment by CoderUni** [comment]
I'll add an option for you to set your own number for tablets with smaller screens. The number I got is what everyone pretty much uses to check if the device is a tablet or not though.

**Comment by CoderUni** [comment]
Version 3.0.5 now supports this. You can set the `maxMobileWidth` to 550 to specify that the mobile device's max width. 
```
MaterialApp(
 home: ResponsiveSizer(
   builder: (context, orientation, screenType) {
     return const HomePage();
   },
   maxMobileWidth: 550,
 ),
);
```
