### ISSUE TITLE
Why 100.sp != (50.sp)*2

### ISSUE THREAD

**Issue by q876625596** [CoderUni/responsive_sizer#12]
I set the width to 50.sp and then to 100.sp and found that they are not 2x

**Comment by q876625596** [comment]
![image](https://user-images.githubusercontent.com/20555239/140605836-65703d9f-96cb-431d-bde7-63f37dbe1895.png)
![image](https://user-images.githubusercontent.com/20555239/140605835-7befc52e-a504-4061-8748-c5bac925800d.png)

**Comment by q876625596** [comment]
![image](https://user-images.githubusercontent.com/20555239/140605840-6376c09a-93ca-4283-b066-d6116f02d132.png)
![image](https://user-images.githubusercontent.com/20555239/140605846-0b286db6-ca27-44dd-b62f-1c839c00c9f4.png)

**Comment by CoderUni** [comment]
Hi @q876625596 , `50.sp * 2` is not equal to `100.sp` because of the way `.sp` is calculated: 
```
  double get sp =>
      this * ((Device height + Device width) + Device pixelRatio * Device aspectRatio) / 2.08) / 100;
        ^<----------------------------------------
        |                                        |
  The this here is the number (50.sp will make this = 50)
```
I hope this clarifies your question :)
