### ISSUE TITLE
How can I make rebuild the screen again when I change the orientation?

### ISSUE THREAD

**Issue by danielrrys** [CoderUni/responsive_sizer#18]
Hello,

I would like to know the difference between using the following :
```
    final bool _isOrientationPortrait =
        Device.orientation == Orientation.portrait; // Not rebuilding

    final bool isOrientationPortrait =
        MediaQuery.of(context).orientation == Orientation.portrait; // Rebuilding

```

Since when using the MediaQuery and I flip my device, it automatically updates the widget, but when using it with the package it doesn't update and I have to be occupying OrientationBuilder. So I would like to know how to update a screen...

I use my ResponsiveSizer like this in my main.dart file : 

```
      [...]
      child: MaterialApp(
        navigatorKey: navigatorKey,
        onGenerateRoute: RouteGenerator.generateRoute,
        [...]
        builder: (BuildContext context, Widget? child) => MediaQuery(
          data: MediaQuery.of(context).copyWith(
            textScaleFactor: MediaQuery.of(context)
                .textScaleFactor
                .clamp(1.0, 1.4),
          ),
          child: ResponsiveSizer(
            builder: (context, orientation, screenSize) =>
                child ?? const SizedBox.shrink(),
          ),
        ),
      ),

```

**Comment by danielrrys** [comment]
For example : 

 ```
Device.orientation == Orientation.portrait
      ? Container(
       // Widget for Portrait
           width: 100.w,
           height: 20.5.h,
           color: Colors.red,
       )
        : Container(
        // Widget for Landscape
            width: 100.w,
            height: 12.5.h,
            color: Colors.green,
       ),
```

Portrait :
![img1](https://user-images.githubusercontent.com/67511557/154482383-bdc18a42-7e64-4d5a-9b9c-0cfc2ea88bd9.jpeg)

Landscape :
![img2](https://user-images.githubusercontent.com/67511557/154482390-c4c99d81-3594-4bef-adc3-f870788b4eb0.jpeg)

Until I make any changes manually, it updates to green...

**Comment by CoderUni** [comment]
Thanks for filing the issue. Did you place `final bool _isOrientationPortrait = Device.orientation == Orientation.portrait;` inside the build method?

**Comment by CoderUni** [comment]
Closing since there is no update after more than a month
