### ISSUE TITLE
Orientation aware

### ISSUE THREAD

**Issue by radvansky-tomas** [CoderUni/responsive_sizer#2]
I had to disable this bit to actually get correct width / height
```
  // Sets screen width and height
    // if (orientation == Orientation.portrait) {
    width = boxConstraints.maxWidth;
    height = boxConstraints.maxHeight;
    // } else {
    //   width = boxConstraints.maxHeight;
    //   height = boxConstraints.maxWidth;
    // }
```

AS far as I know then LayoutBuilder is orientation aware...ie width is always width and you should not artificially change it.

**Comment by CoderUni** [comment]
Thanks for bringing this issue up. This will be fixed on the next version.

**Comment by CoderUni** [comment]
Thanks for bringing this up to me. The `width` and `height` parameters are used for calculating `Adaptive.w` and `Adaptive.h`. I've renamed both of them to `adaptiveWidth` and `adaptiveHeight`. This issue is now fixed in the latest version (^2.0.1). `width` and `height` parameters are now set with the correct `width` and `height`.

**Comment by radvansky-tomas** [comment]
if anyone is interested in orientation aware sizer: https://pub.dev/packages/flutter_sizer/versions/1.0.0

**Comment by CoderUni** [comment]
@radvansky-tomas Its a really good package. Congrats :tada: 

Would it be ok to use some of your improvements in your package? I'm going to experiment with your `.dp` implementation. I'd like to try it out.

**Edit:
I noticed that you haven't update the right hand corner of your repo in the about page. It still says `responsive_sizer`

**Comment by radvansky-tomas** [comment]
@CoderUni Of course ;) use what you can...I spent couple hours investigating good .dp option...best option would be to use less "magic" numbers...but I could not find proper documentation. Specially when you want to use is across all platforms. 

PS. yep thx ,will try to update it with next release
