### ISSUE TITLE
How to use responsive sizer when using routes and initialroute instead of home in MaterialApp?

### ISSUE THREAD

**Issue by charcoast** [CoderUni/responsive_sizer#21]
I'm having trouble using the library.

I receive the following error:
```
No MediaQuery widget ancestor found.
LayoutBuilder widgets require the MediaQuery widget ancestor.
The specific widget that could not find a MediaQuery ancestor was:
   LayoutBuilder
The ownership chain for the affected widget is: "LayoutBuilder ← OrientationBuilder ← LayoutBuilder
   ← ResponsiveSizer ← MyApp ← [root]"
No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of().
This can happen because you have not added a WidgetsApp, CupertinoApp, or MaterialApp widget (those
widgets introduce a MediaQuery), or it can happen if the context you use comes from a widget above
those widgets.
```

**Comment by harguus** [comment]
> I'm having trouble using the library.
> 
> I receive the following error:
> 
> ```
> No MediaQuery widget ancestor found.
> LayoutBuilder widgets require the MediaQuery widget ancestor.
> The specific widget that could not find a MediaQuery ancestor was:
>    LayoutBuilder
> The ownership chain for the affected widget is: "LayoutBuilder ← OrientationBuilder ← LayoutBuilder
>    ← ResponsiveSizer ← MyApp ← [root]"
> No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of().
> This can happen because you have not added a WidgetsApp, CupertinoApp, or MaterialApp widget (those
> widgets introduce a MediaQuery), or it can happen if the context you use comes from a widget above
> those widgets.
> ```

user this package: https://pub.dev/packages/responsive_sizer

**Comment by CoderUni** [comment]
I'm working on a fix for this issue and will update you once it's finished. Thank you for reporting the issue to me.

**Comment by CoderUni** [comment]
@charcoast Have you tried placing the `ResponsiveSizer` widget inside `MaterialApp`? I've also published a newer version of the package that is less restrictive; it allows the `MaterialApp` to be wrapped by `ResponsiveSizer` now.
