### ISSUE TITLE
 ../../../development/tools/flutter/.pub-cache/hosted/pub.dartlang.org/responsive_sizer-3.0.6+1/lib/src/helper.dart:56:33: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.

### ISSUE THREAD

**Issue by hassanyassiin** [CoderUni/responsive_sizer#23]
when I made flutter upgrade, then this errors shows, but the app is still running normally!!

**Comment by CoderUni** [comment]
Thanks for filing this issue. It has now been fixed since ^3.0.7

**Comment by hassanyassiin** [comment]
Thanks for your response, but the error still shown.

**Comment by CoderUni** [comment]
I looks like the problem is caused by upgrading to flutter 3: https://github.com/flutter/flutter/issues/103561. I added some changes to add support for flutter 3 as well.
