### ISSUE TITLE
Add Desktop ScreenType

### ISSUE THREAD

**Issue by tlvenn** [CoderUni/responsive_sizer#25]
Hi,

It seems like it would be useful to add the `Desktop` ScreenType.

**Comment by CoderUni** [comment]
Thanks for filing a feature request. It's now supported in `^3.1.1`. Make sure to set the `maxTabletWidth` parameter.

**Comment by tlvenn** [comment]
Great thanks !

**Comment by evertonfoz** [comment]
Hi. I set `maxTabletWidth` parameter, but always return `tablet` screenType. Can you help me?

**Comment by CoderUni** [comment]
Hi @evertonfoz, which version of the package are you using? Also, could you share a quick snippet of your code? Thanks!

**Comment by evertonfoz** [comment]
Hi @CoderUni , thanks for response. I am using the `responsive_sizer: ^3.1.1 `version and the snippet code is:

    
```
return RobotDetector(
      child: ResponsiveSizer(
          maxMobileWidth: 599,
          maxTabletWidth: 1199,
          builder: (context, orientation, screenType) {
            return MaterialApp(
              debugShowCheckedModeBanner: false,
              navigatorObservers: [seoRouteObserver],
              home: MaterialApp.router(
                color: kBrandColor,
                theme: themeApp(),
                debugShowCheckedModeBanner: false,
                routeInformationParser: Modular.routeInformationParser,
                routerDelegate: Modular.routerDelegate,
              ),
            );
          }),
    );
```
