### ISSUE TITLE
two ResponsiveSizer

### ISSUE THREAD

**Issue by mbfakourii** [CoderUni/responsive_sizer#26]
hi , if this package is used in another package and this package and another package are used in the program, there will be a problem in the context and the page size will be messed up, please check if ResponsiveSizer exists, do not set it anymore!

```
mian (my app)
     ResponsiveSizer (my app)
         another package (use ResponsiveSizer)
```

**Comment by CoderUni** [comment]
Thanks for filing an issue. Could you provide a quick example of a reproducible code and the error (if any) along side it?

**Comment by CoderUni** [comment]
Closing since there is no response for a month.
