### ISSUE TITLE
Sp and Dp way different than with sizer and are not interchangable 

### ISSUE THREAD

**Issue by altunyurt** [CoderUni/responsive_sizer#27]
I was using sizer, then migrated to responsive sizer.  With sizer 1.sp was around 1.2 px but as you can see below, it's around 1/20th of it with responsive sizer. Also i can not replace sp with dp since there's a huge difference between dp and sp.  

Following are the values i get with responsive sizer.
```
1.sp 0.060366202945990176  (1.21 with sizer)
1.dp 192.0 
1.h 7.52 
1.w 3.6 
Device.pixelRatio 3.0 
Device.aspectRatio 0.4787234042553192 
Device.height 752.0 
Device.width 360.0
```

My initialization code is as follows: 

```flutter 
    return ResponsiveSizer(                                                                        
      builder: (context, orientation, deviceType) {       
        return GetMaterialApp(                                                                     
          title: 'My app',
          theme: ThemeData(                                                                        
              primarySwatch: Colors.grey,                                                          
              visualDensity: VisualDensity.adaptivePlatformDensity,
              textTheme: Theme.of(context)
                  .textTheme                                                                       
                  .copyWith(                                                                       
                    bodyLarge: TextStyle(fontSize: Defaults.bigFontSize), // 16.sp
                    bodyMedium: TextStyle(fontSize: Defaults.fontSize),  // 14.sp
                    bodySmall: TextStyle(fontSize: Defaults.smallFontSize), // 12.sp
                  )                                                                                
                  .apply(
                    fontSizeFactor: 1.sp,
                  ),
              dividerColor: Colors.transparent),
          home: HomeView()
        );
    }
);         
 
```

**Comment by altunyurt** [comment]
For dp, there seems to be an error in calculation. The divisor should be screen density instead of pixel ratio.
 
https://github.com/CoderUni/responsive_sizer/blob/main/lib/src/extension.dart#L63 
https://material.io/design/layout/pixel-density.html#pixel-density-on-android

And for sp it seems the same screen density - pixel ratio confusion is the culprit. With the values from material design page 
the calculation would be something like 

```dart
 double get sp =>
      this *
      (((h + w) + (240 * Device.aspectRatio)) / 2.08) /
      100;
```
which would then give 1.sp = 0.70 for the values above. Removing division by 2.08  would give a very acceptable 1.sp = 1.45

**Comment by CoderUni** [comment]
Thanks for creating the issue. I'll experiment more around this before I add the implementation since this would be a breaking change for existing users.

**Comment by LocaFoxNick** [comment]
Hi, any update on this issue?

**Comment by CoderUni** [comment]
Hi @LocaFoxNick, I plan to slowly introduce this in the future without breaking the existing apps that use previous versions of this package. Will be updating the package in a month or two to support this.

**Comment by CoderUni** [comment]
@altunyurt @LocaFoxNick Currently, there doesn't seem to be a way to obtain a device's screen width in inches. This is needed to calculate `dp` and `sp` according to [Material design specs](https://m2.material.io/design/layout/pixel-density.html#pixel-density-on-android). At the moment, I've filed an [issue](https://github.com/flutter/flutter/issues/131111) in the Flutter repo. Hoping that they could help us find a way to retrieve a device's screen size in inches.

**Comment by CoderUni** [comment]
@altunyurt In the meantime, I added `.spa` which uses your way of calculating `.sp`.

**Comment by CoderUni** [comment]
Closing inactive issue.
