### ISSUE TITLE
The Device Class variables apsectRatio, width, and height all Resize when Textfieldforms are used.

### ISSUE THREAD

**Issue by decomplosion** [CoderUni/responsive_sizer#30]
This isn't specific to Textformfields but its the easiest way to reproduce the failure.   Essentially when the screen/widgets are built initially everything is great, but then after opening up a Textformfield on any screen it seems that the Device value gets corrupted and all my text shrinks (likely due to the height changing in the widget).  

If I replace Device with MediaQuery.of(context).size then I see no issues.  

Because Device is used in quite a few places this also impacts .sp, .h, .w, .vmin and .vmax.

Let me know if you need more info, but through some trial and error I am pretty confident that my assessment should lead you down the right path to the actual bug.  Once I created my own .sp the text works great across multiple devices and does not change when using textformfields.

Below is my implementation to resolve the issue
int fontSize = 21;
    double sp = ((((fontSize*MediaQuery.of(context).size.height/100) + (fontSize*MediaQuery.of(context).size.width/100)) + (Device.pixelRatio * MediaQuery.of(context).size.aspectRatio))/2.08)/100;
   

style:TextStyle(fontFamily: "Cinzel",fontSize: (fontSize*sp)), //21.sp),

**Comment by CoderUni** [comment]
Could you provide a reproducible sample code for this? I tried adding a `TextFormField` in the example app and it seems like the sizes of the container and text remained the same. 

Here is the sample code I've tried:
```dart
import 'package:flutter/material.dart';
import 'package:responsive_sizer/responsive_sizer.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ResponsiveSizer(
      builder: (context, orientation, screenType) {
        return MaterialApp(
          title: 'Responsive Sizer Example',
          theme: ThemeData(
            primarySwatch: Colors.blue,
          ),
          home: Home(),
        );
      },
      maxTabletWidth: 900, // Optional
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    late final String screenTypeText;

    switch (Device.screenType) {
      case ScreenType.mobile:
        screenTypeText = "My screen's type is Mobile";
        break;
      case ScreenType.tablet:
        screenTypeText = "My screen's type is Tablet";
        break;
      // ScreenType can only be desktop when `maxTabletWidth`
      // is set in `ResponsiveSizer`
      case ScreenType.desktop:
        screenTypeText = "My screen's type is Desktop";
        break;
    }

    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        children: [
          Container(
            height: Adaptive.h(12.5), // or 12.5.h
            width: 50.w, // or Adaptive.w(50)
            color: Colors.black,
          ),
          Text(
            "This text is responsive",
            style: TextStyle(fontSize: 18.sp), // or Adaptive.sp(12)
          ),
          Text(
            "w=${100.w} h=${100.h}",
            style: TextStyle(fontSize: 12.sp),
          ),
          Device.orientation == Orientation.portrait
              ? Text("My orientation is Portrait")
              : Text("My orientation is Landscape"),
          Text(screenTypeText),
          TextFormField(),
        ],
      ),
    );
  }
}
```

**Comment by CoderUni** [comment]
Closing inactive issue.
