### ISSUE TITLE
Changing the device text size setting affects the outputted UI.

### ISSUE THREAD

**Issue by ShinMyth** [CoderUni/responsive_sizer#32]
I'm not sure if this is a valid issue or just the expected result since I'm not sure of the correlation between the text size setting and the device's pixel density. Nevertheless here are my findings:

iPhone 11 Simulator- Default text size
![Simulator Screen Shot - iPhone 11 - 2023-07-24 at 09 44 06](https://github.com/CoderUni/responsive_sizer/assets/45448192/85234691-9aaf-4b89-a9b3-f092f7a8489a)
![Simulator Screen Shot - iPhone 11 - 2023-07-24 at 09 45 09](https://github.com/CoderUni/responsive_sizer/assets/45448192/1b0170c6-931d-4cc2-8572-df4c2b229e53)

iPhone 11 Simulator - 3 sizes up
![Simulator Screen Shot - iPhone 11 - 2023-07-24 at 09 45 44](https://github.com/CoderUni/responsive_sizer/assets/45448192/6cf52a05-be58-4733-90c9-7f41ae737f25)
![Simulator Screen Shot - iPhone 11 - 2023-07-24 at 09 45 19](https://github.com/CoderUni/responsive_sizer/assets/45448192/0cf8f8c9-93c5-45b8-be48-2eb75d8e2047)

**Comment by CoderUni** [comment]
You are correct. There is no correlation between the font size setting and the device's pixel density or its aspect ratio. The font is larger because of the internal scaling that your iPhone applies to the text. I believe the same effect will happen with `fontSize: 24`. I don't think using `.sp` or `.dp` can prevent that internal scaling.

**Comment by ShinMyth** [comment]
> You are correct. There is no correlation between the font size setting and the device's pixel density or its aspect ratio. The font is larger because of the internal scaling that your iPhone applies to the text. I believe the same effect will happen with `fontSize: 24`. I don't think using `.sp` or `.dp` can prevent that internal scaling.

Thank you for responding, upon further research it seems that the device text size setting only affects the MediaQuery textScaleFactor and has nothing to do with the package, therefore I'm closing this issue.

But here is a workaround for those who might want their UI to stay the same regardless of the device text size that the user sets:
![Screen Shot 2023-07-28 at 3 12 25 PM](https://github.com/CoderUni/responsive_sizer/assets/45448192/110d1bc9-c871-44ea-99e7-c62cb72836aa)

**Comment by CoderUni** [comment]
Thanks for sharing the workaround!
