### ISSUE TITLE
ScreenType.desktop Issue 

### ISSUE THREAD

**Issue by nikirana22** [CoderUni/responsive_sizer#33]
I want to make different UI on the bases of Screen in the current case I'm running my app on Web and I'm doing this with the help of Device.screenType but in current case i'm getting SceenType.mobile because of the logic that you wrote in if check in setScreenSize method in helper.dart class. Please correct me if i'm wrong 
![Screenshot (3833)](https://github.com/CoderUni/responsive_sizer/assets/102287515/6d4a9eff-6332-4d8a-9c6d-f21a91e3d5b4)

**Comment by CoderUni** [comment]
Does [Device.deviceType](https://github.com/CoderUni/responsive_sizer/blob/198f88b5b7aef46c3d841b13b71d577a16f4f2e2/lib/src/helper.dart#L21C26-L21C36) solve your issue? It seems to be missing in the docs. I'll update the docs soon to include `Device.deviceType`.  Thanks.

**Comment by nikirana22** [comment]
I know about Device.deviceType but i don't want to make the UI different on the Bases of platform but on the bases of Device size.

**Comment by CoderUni** [comment]
Have you tried setting the `maxMobileWidth` and `maxTabletWidth`? The docs can be found [here](https://github.com/CoderUni/responsive_sizer#responsivesizer)

**Comment by CoderUni** [comment]
Closing inactive issue

**Comment by PawnBreak2** [comment]
> Have you tried setting the `maxMobileWidth` and `maxTabletWidth`? The docs can be found [here](https://github.com/CoderUni/responsive_sizer#responsivesizer)

this is not solving the issue unfortunately. On web it's not considering maxTabletWidth when switching Device.screenType (it's always set on tablet for widths > 599)

**Comment by CoderUni** [comment]
> > Have you tried setting the `maxMobileWidth` and `maxTabletWidth`? The docs can be found [here](https://github.com/CoderUni/responsive_sizer#responsivesizer)
> 
> this is not solving the issue unfortunately. On web it's not considering maxTabletWidth when switching Device.screenType (it's always set on tablet for widths > 599)

Were you able to make sure that `ResponsiveSizer` rebuilds whenever your window resizes? I'm unable to reproduce it on my end.
