### ISSUE TITLE
Responsive sizer stops working properly, resizing issues

### ISSUE THREAD

**Issue by S-A-Hanifah** [CoderUni/responsive_sizer#36]
when changing screen orientation the widgets doesnt follow my settings.  when tilted back and forth the ui just messed up.

ps never had this issue before. been using this package since the beginning.

**Comment by CoderUni** [comment]
I'll take a look at it. Did this issue pop up in the latest version? (^3.3.0)

Could you also provide a simple reproducible sample?

**Comment by CoderUni** [comment]
Tested this again and couldn't reproduce the issue.
