### ISSUE TITLE
Undefined name 'View'.   

### ISSUE THREAD

**Issue by htbeazxcq123** [CoderUni/responsive_sizer#38]
I used respinsive_sizer 3.3.0 in my flutter project,when I run it, this error occurred：helper.dart:71:18: Error: Undefined name 'View'.
    pixelRatio = View.of(context).devicePixelRatio;

**Comment by laloriru** [comment]
Hello, I also having this issue:

```
I used respinsive_sizer 3.3.0 in my flutter project,when I run it, this error occurred：helper.dart:71:18: Error: Undefined name 'View'.
pixelRatio = View.of(context).devicePixelRatio;
```

I wonder if someone could make it work and possible solution. Please

**Comment by CoderUni** [comment]
Thanks for filing the issue. Try checking if this bug still exists on the new version: ^3.3.1
