### ISSUE TITLE
Defined Size as dp and sp not as percentage.

### ISSUE THREAD

**Issue by zyllus17** [CoderUni/responsive_sizer#4]
I see your package to defined `size` is as a `percentage` (Max to define the size is 100, ex: 100.0.w / 100.0.h --> it's mean the size is 100% / full screen). But can we specify the size is not using a percentage but using a `dp` for width and height and a `sp` for the font?

For example, if in the mockup get the size for the font is `14`, so we can't implement your package like this:
```style: TextStyle(fontSize: 14.0.sp), // This is not sp, but the font size is 14% from the screen. So it not accurate with the size in the mockup that created by designer.```

Also if in the mockup get width is `100` and height is `50` for the `Button`, so we can't implement your package like this:

```
SizedBox(
   width: 100.0.w,  // This is not accurate with the size in the mockup that created by designer.
   height: 50.0.h, // This is not accurate with the size in the mockup that created by designer.
   child: RaisedButton(),
),
```
I think this is the major issue.

This is a issue mentioned in the original Sizer package, I have the same issue, I want to use exact values from Design and the package should scale accordingly. Can you please tell me how I can do this?
I have heard, extensions can be used but I am not able to work it out.

If you could show an example, I would be highly grateful.

**Comment by CoderUni** [comment]
Thanks for opening this issue. The problem with dp is that I don't know the exact calculations of dp in your design. I would suggest manually mapping them yourself through trial and error. Eg: Check the ratio between the design's dp to flutter's lp.

**Comment by zyllus17** [comment]
If you would like, I can share the Figma design with you.

**Comment by CoderUni** [comment]
Its ok, you don't have to share the design with me. You could fork this repo and try manually adjusting the values to fit your design's dp.
