### ISSUE TITLE
Sizes are not updating when rotating the device

### ISSUE THREAD

**Issue by sumitanaiya** [CoderUni/responsive_sizer#40]
If we use MediaQuery.of(context).size then the size is automatically updated when rotating the device, but when using Adaptive.w or .w the sizes are not automatically updating on rotation

**Comment by CoderUni** [comment]
Did you wrap `MaterialApp` with `ResponsiveSizer`? If you did and the problem still persists, you have to rebuild your widget by using [OrientationBuilder](https://api.flutter.dev/flutter/widgets/OrientationBuilder-class.html) so that it is using the updated `Adaptive.w` state. 

Try doing this:
```dart
OrientationBuilder(builder: (context, orientation) {
   return MyWidget(
                width: // Your Adaptive.w here
              );
});
```

**Comment by CoderUni** [comment]
Closing since there's been no response for two weeks.
