### ISSUE TITLE
The package rebuild the widget tree when using it with go router

### ISSUE THREAD

**Issue by leulabay1** [CoderUni/responsive_sizer#41]
The ResponsiveSizer is wrapped around the MatrialAppRouter which makes it vulnerable to rebuild the whole app when a textfield is focused.

`ResponsiveSizer(
          builder: (context, orientation, deviceType) {    
            return MaterialApp.router(
              title: "Hawk",
              theme: ThemeClass.lightTheme,
              routerConfig: GoRouter()),
            );
          }
        ),`

**Comment by CoderUni** [comment]
Have you tried using [ShellRoute](https://pub.dev/documentation/go_router/latest/go_router/ShellRoute-class.html)? Try using `ResponsiveSizer` in ShellRoute's builder method instead.

**Comment by leulabay1** [comment]
I was using the responsive sizer in my theme data too so I had to wrap the whole widget tree with `ResponsiveSizer`

But I found a solution which is Initializing and providing the Router with a separate class like this. Now whenever the widget tree rebuilds the router will not be initialized as it's above the `ResponsiveSizer`.

```
 RepositoryProvider(
          create: (context) => AppRouter(),
          child: ResponsiveSizer(builder: (context, orientation, deviceType) {
            return MaterialApp.router(
              title: "Example",
              theme: ThemeClass.lightTheme,
              routerConfig: context.read<AppRouter>().router,
            );
          }),
        ),
```
