### ISSUE TITLE
The package doesn't work when using const constructors for widgets

### ISSUE THREAD

**Issue by liranzairi** [CoderUni/responsive_sizer#42]
**Reproduce:**
Take the example code from this package and give `Home` widget a const constructor. Also create the instance of it with const. Full example:
```dart
import 'package:flutter/material.dart';
import 'package:responsive_sizer/responsive_sizer.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ResponsiveSizer(
      builder: (context, orientation, screenType) {
        return MaterialApp(
          title: 'Responsive Sizer Example',
          theme: ThemeData(
            primarySwatch: Colors.blue,
          ),
          home: const Home(),
        );
      },
      maxTabletWidth: 900, // Optional
    );
  }
}

class Home extends StatelessWidget {
  const Home();

  @override
  Widget build(BuildContext context) {
    late final String screenTypeText;

    switch (Device.screenType) {
      case ScreenType.mobile:
        screenTypeText = "My screen's type is Mobile";
        break;
      case ScreenType.tablet:
        screenTypeText = "My screen's type is Tablet";
        break;
      // ScreenType can only be desktop when `maxTabletWidth`
      // is set in `ResponsiveSizer`
      case ScreenType.desktop:
        screenTypeText = "My screen's type is Desktop";
        break;
    }

    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        children: [
          Container(
            height: Adaptive.h(12.5), // or 12.5.h
            width: 50.w, // or Adaptive.w(50)
            color: Colors.black,
          ),
          Text(
            "This text is responsive",
            style: TextStyle(fontSize: 18.sp), // or Adaptive.sp(12)
          ),
          Text(
            "w=${100.w} h=${100.h}",
            style: TextStyle(fontSize: 12.sp),
          ),
          Device.orientation == Orientation.portrait
              ? Text("My orientation is Portrait")
              : Text("My orientation is Landscape"),
          Text(screenTypeText),
        ],
      ),
    );
  }
}
```
Then run it in web. Notice that when you change the window size, the responsive text size doesn't change as it should.
This happens because Flutter's build cycle doesn't visit const children. It's an important optimization used to enhance performance and Flutter highly recommends using it (see https://docs.flutter.dev/perf/best-practices, https://www.youtube.com/watch?v=IOyq-eTRhvo)

**Comment by CoderUni** [comment]
You need the `Home` widget to rebuild. Removing `const` solves the issue. If you've set your `Home` widget as a const, it's not going to "update" or rebulid when the window size changes since you've marked it as a constant. Having it rebuild again won't really make that much of an impact since Flutter is fast. Only use `const` if you don't need the widget to rebuild.

**Comment by liranzairi** [comment]
@CoderUni Of course it won't make a difference in a tiny single page example app. However in more complex widget trees, if rebuilds happen often (e.g changing the window size, animation, etc) you'll definitely notice performance degradation. That's why using const is one of the basic practices recommended by Flutter.

**Comment by CoderUni** [comment]
It is a best practice. However, you can only use it on children that don't need to be rebuilt. In this scenario, you have no choice. If you do not rebuild your `Home` widget, then how would your `responsive text size` update whenever the window size changes? This is the same thing with animations. There is a reason why animation widgets have a builder function. To optimize it, you add a `const` to certain parts of the widget that don't need to be rebuilt.

**Comment by liranzairi** [comment]
You're correct that the widget needs to rebuild if the window size changes, but the way you're currently doing it isn't ideal at all because it causes the widget to rebuild every time the parent does for any reason. You need a better approach that allows rebuilds only when needed - i.e when the window size/orientation changes.

This principle is also used in other packages such as Provider, where you have `context.select(...)` in order to make sure the widget rebuilds in reaction to only certain state changes and not all of them.

My suggestion to you is to either change `ResponsiveSizer` to be an InheritedWidget or change `Device` to be a Provider so widgets can depend on it. If you're interested I can help with a PR.

**Comment by CoderUni** [comment]
I'm interested in your proposed changes. I just don't think it would be possible to add those changes while making `ResponsiveSizer` intuitive and easy to use for other people. If you're able to do so, I'd be happy to merge the changes. `ResponsiveSizer` uses `LayoutBuilder` and `OrientationBuilder` behind the scenes. You can start [here](https://github.com/CoderUni/responsive_sizer/blob/aa35a214716a50e221b7a17d8429fe7431fc5e88/lib/src/widget.dart#L43). Thanks.
