### ISSUE TITLE
ResponsiveSizer triggers rebuild on IOS when app is sent to background

### ISSUE THREAD

**Issue by pamafe1976** [CoderUni/responsive_sizer#44]
On IOS, When using ResponsiveSizer as parent of GetMaterialApp, a rebuild is triggered after the app has gone to background. This causes all type of build error for components down the tree. 

Why is this rebuild necesary?
It does not happen in Android.

Regards

**Comment by CoderUni** [comment]
Could you show me your code with `ResponsiveSizer` and `GetMaterialApp`?

Try wrapping the Home page with `ResponsiveSizer` instead of `GetMaterialApp` as well. That might fix the issue.
```dart
GetMaterialApp(
    home: ResponsiveSizer( //Home page here )
)
```

**Comment by pamafe1976** [comment]
This problem is not caused by ResponsiveSizer, since any access to context in the build seems to trigger a build when app goes to background in IOS.

I have created an issue in flutter [#149555](https://github.com/flutter/flutter/issues/149555)

This may end up being a flutter bug or normal platform behavior.
