### ISSUE TITLE
Use of the package

### ISSUE THREAD

**Issue by titoworlddev** [CoderUni/responsive_sizer#5]
Hello I wanted to ask a question about the use of the package. I have been using the package and it is doing very well, the problem is that I don't know if I am using it well. Since the same thing happened to me with the other package of sizer. That is, I cannot adapt my application to all screens perfectly, and I think it is because I do not use it well. So my question would be, should I put the ResposiveSizer widget on every screen where I use it or just put it in the main as it works in the example?

**Comment by CoderUni** [comment]
Thanks for reaching out, `ResponsiveSizer` should only be placed once on top of `MaterialApp`. What the widget really does is get the constraints and orientation of your device so that you can have access to 10.h or Device orientation in widgets below the `MaterialApp`

**Comment by titoworlddev** [comment]
Ah okay, so I thought it was used but since I can't adapt the app as I want, I prefer to ask. By the way, I'm going to open another bug ticket to discuss another issue. Sorry to be heavy, but the package helps a lot and I like it, I just want it to work perfectly.

**Comment by CoderUni** [comment]
Sure, open another one.
