### ISSUE TITLE
Handle master detail pattern

### ISSUE THREAD

**Issue by gedw99** [CoderUni/responsive_sizer#7]
Works like this:

https://blogs.windows.com/windowsdeveloper/2017/05/01/master-master-detail-pattern/

https://en.m.wikipedia.org/wiki/Master%E2%80%93detail_interface

On mobile you navigate from the master to the detail page.

On desktop of tablet , you have master and detail page on the same screen.

This is a very common need …

routing can get tricky to do it .

typicalky I have seen it done I using a different scaffold for each which is not DRY as we would like . It would be awesome if that can be abstracted to a degree . 

my feeling is that a higher level component is created that uses your library to do both scenarios in a reusable way .

Thoughts ? 

Would be great to end up with an example showing it

**Comment by gedw99** [comment]
Prior art 👍 

https://github.com/MaikuB/master_detail_scaffold

**Comment by CoderUni** [comment]
Thanks for opening an issue, this is quite hard to implement. Is there any reason why you wouldn't want to use the `master_detail_scaffold` and `responsive_sizer` together?

**Comment by CoderUni** [comment]
Closing since there is no reply after 6 days.

**Comment by gedw99** [comment]
Sorry missed this

I am proposing using the 2 together 

but integrating it into your project
