### ISSUE TITLE
Extension malfunction, still...

### ISSUE THREAD

**Issue by titoworlddev** [CoderUni/responsive_sizer#9]
I don't know why it closes it, it still works badly, more than anything I mean the calculation it does for the .sp function
it does not work well, as it is now it would be better to have left it as before and I will show you.

I already said that you had to take into account the two sizes of the screen, it is useless to use only the width because when the height changes the text should change with it, that is to adapt well.

But keep with the idea of ​​only taking width into account and now it works worse. It has been good to use pixelDensity, that is correct but the calculation is not well done and as I said I will show you with screenshots that I have made using your method and using mine with two independent functions, a .ts2 call that uses your package for the measures and the other just uses MediaQuery to have more real measures, but they both work fine.

Here I attach the photographs, two photos are in an android studio emulator where only the height changes and the other two are two real devices.

Also say that the sizes have been set in the large android studio emulator and in portrait mode, so you can see that only in that photo, all the font sizes are the same.

![Web 1920 – 1](https://user-images.githubusercontent.com/70041483/121188642-9a40ee80-c869-11eb-980c-eecd4a31ced5.png)
![Web 1920 – 2](https://user-images.githubusercontent.com/70041483/121188678-a167fc80-c869-11eb-80bc-4a29e1eac74e.png)
![Web 1920 – 3](https://user-images.githubusercontent.com/70041483/121188696-a5941a00-c869-11eb-9475-98b70d6d3793.png)
![Web 1920 – 4](https://user-images.githubusercontent.com/70041483/121188709-a7f67400-c869-11eb-9cdf-5d60c899d084.png)

As you can see, the functions I have created are almost perfect, but almost perfect is better than totally bad.

I also want to say that the .h and .w functions now work fine, but you could also think of using pixelDensity for this, since not all screens have the same pixel density even if they have the same dimensions.

All this I leave in this drive link where the screenshots are so you can see them well, and I also attach there the folder of the project where I have done the tests. Feel free to try and if my function convinces you, do not hesitate to use it in your package, I just want to help you.

Here the project link: https://drive.google.com/file/d/1WENQoD4MmwUnEZazOpeD7qksGZUbFBbA/view?usp=sharing

**Comment by CoderUni** [comment]
Thanks for the suggestion. I'll take a look at it. Would you be able to place the project in a github repo instead of in google drive?

**Comment by titoworlddev** [comment]
Yes, I can put it, but it does not change anything, if you download the drive it is the same and it does not have a virus, in case that is the problem.

Also here is the github link: https://github.com/Hekhy/Sizer-test

I see that there are files that won't let me upload them, and it does not let me upload them because it tells me that they are hidden, the truth is I'm not very good with github even so I think it would be better to use the drive one, if not, maybe you can do a `flutter create .` and test if it creates the missing files.

**Comment by CoderUni** [comment]
The .sp implementation has been changed since ^3.0.0 to address the issue you're currently having:
`double get sp => this * Device.width / Device.pixelDensity / 100;`

Update to the latest version and check if you still have a problem

**Comment by titoworlddev** [comment]
I have used the latest version to do the tests, that is where the problem I mentioned and the solutions are, all in my shared project.

**Comment by CoderUni** [comment]
You're using the old implementation of `.sp`:

`double get sp1 => this * (wi / 3) / 100;`

This is the code you're using for responsive_sizer:
`ContainerTest(fontSize:70.sp1)`

**Comment by titoworlddev** [comment]
No, I am on version 3.0.2 and this method is not there.
I only put that to compare, but if you comment on that line and uncomment the one just above that, as you can see, is the method of version 3.0.2, you will see that it does not go well as seen in the screenshots.
The captures are made using version 3.0.2, that .sp1 method is an error for me to have left it because it does not work, I simply wanted to compare with the old, so I told you that it was almost better to use the old one before the new one.
But you just have to try it for yourself and you will see it, just delete that .sp1 method, it does not work and the version 3.0.2 method does not work either, that is what I want to get to.
But if you don't try it, you won't see it. It's no use if you just look at the code...

I have already updated the github repository if you downloaded it from there it is already removed that .sp1 method and you can try it as it is in the screenshots.

And the google drive file also updated here:https://drive.google.com/file/d/12FEh-cnbwGupXyKeJofuf5_MipxhmI6D/view?usp=sharing

**Comment by CoderUni** [comment]
Your implementation of .ts1 and .ts2 in the example made the font look really small. I've edited the implementation to this:
`this * (((h + w) + (Device.pixelRatio * Device.aspectRatio)) / 2.08) / 100;`

This seems to be a better way of doing it. I will be releasing this update in a few hours. Thanks for creating this issue.

**Comment by titoworlddev** [comment]
I congratulate you on the change, now the size of the text does adapt well.
Although you mention that the size seems really small and it is not like that, in the project I put four Container () so that you could check that the size of the letter with the function that I did is almost the same as the size of the letter when you do not use no function, and in my opinion this is the correct thing because what is sought is that the text adapts to all screens but putting a logical number, I have updated my project with the function that you said you are going to use in the next update as you can see here:
![edsd](https://user-images.githubusercontent.com/70041483/121520871-b83a5a80-c9f3-11eb-8a66-24b96ee5fbd5.png)

But it is not normal for 10.ts1 to be as large as this:
![fdwwe](https://user-images.githubusercontent.com/70041483/121520888-be303b80-c9f3-11eb-9c53-3d8fd0e23dcb.png)

Think about it.

Anyway, I congratulate you again since now the text adapts well to the different screens.

**Comment by CoderUni** [comment]
No need to congratulate me for it, this update is your work. Thank you for sharing it. I will be looking at the difference between the two before publishing new changes.

**Comment by titoworlddev** [comment]
A pleasure to have helped you so that everyone can enjoy a package that gives many facilities to those of us who develop with flutter, now it is easy to do so.

**Comment by CoderUni** [comment]
I tested your function again and it looks really small in the example. This seems to be because the pixel ratio of your emulator is really low. You seem to be using the android emulator small on the screenshot above. Phones aren't that small anymore. Looks like lowering the number to from 12 to 2.08 would be a better solution.

**Comment by titoworlddev** [comment]
No, if you look at all the screenshots there is the Container () with the title "Normal" and the last two on the right with the title "ts1 function and ts2 function" if you notice they are the same size in all Photographs are not small, they are as they would have to be if the function is not used.
But hey do what you want, it's your package not mine...

You also say that the dimensions of the emulator with which I have created the example are very small, and I have a Xiaomi Redmi Note 7, a fairly new device, which has dimensions of 392 width x 803 heigth and the emulator where I have created the example 400 width x 752 height, the difference is not much, but I also put four different examples so that you could see perfectly how the functions I made adapt and maintain a logical size with respect to the normal size without the function, the tests are there but as I already said it's your package not mine.
At least now if it fits well so I'm happy.

**Comment by CoderUni** [comment]
I used my example app included in the library as the benchmark. I tried your example and it shows the same results with the example app. Wanna take a look at it?

**Comment by titoworlddev** [comment]
Okay, I'll take a look, but it seems strange to me because I have tested it on four different devices, two are emulators and two are real devices and one is quite new, and it looked good on all of them.

**Comment by CoderUni** [comment]
Closing since there has been no further objection for 5 days.

**Comment by titoworlddev** [comment]
Hi @CoderUni,
I'm sorry it took so long, lately I couldn't work on this,
but i've been testing yesterday and today.
I realized that you are right and with my method this:
`double get ts1 => this * ((((Sizer.h + Sizer.w) + (Sizer.pixelRatio * Sizer.aspecRatio)) / 2) / 6) / 100;`
if it looks very small, but doing tests I realized that this is because I use MediaQuery to know the pixerRatio and the same for everything else.

And you do it differently, using for example this method for the pixelRatio:
```
static double get pixelRatio {
    return WidgetsBinding.instance?.window.devicePixelRatio ?? 1;
  }
```

This is neither good nor bad from what I have been able to see, since the measurements that are given in the application that I did test are the same, both with your method and mine are the same as you can see here:
![Screenshot_1624033458](https://user-images.githubusercontent.com/70041483/122590870-6da78680-d062-11eb-81ac-88d097bb1810.png)

But when I do the operation to do my ts1 method, if I use MediaQuery, I don't know what happens internally, but even if I do the same operation as you, my letter looks bigger, that's why I divided everything in the operation by 6 and that's why you saw it so small.
![Screenshot_1624033525](https://user-images.githubusercontent.com/70041483/122591027-a7788d00-d062-11eb-903a-299b2b18c16e.png)

Here you can see in the example how the measurements are so different using the same operation as you can see here:
![egwwegwdg](https://user-images.githubusercontent.com/70041483/122591131-d1ca4a80-d062-11eb-9bf3-8af67f4e6ad4.jpg)

As you can see they are the same operation, but as I said before I get the measurements through MediaQuery and that is the big difference between the two functions and that is why it looked very small when you used your input to get the measurements from the phone but my function ts1.

So right now your package is perfect in my opinion, thank you very much for taking the time to pay attention to the users, that improves things a lot.

Please don't ever change that part. XD
